### ISSUE TITLE
angelloLite

### ISSUE THREAD

**Issue by elyphas** [jokade/angulate2-examples#1]
06_angelloLite, lack the fastOptJS in "angelloLite(angelloLite, Compile) in build.sbt", I suppose, so I added it, but  when I compile this give some errors. and I can't run it, 

this the error: 

"EXCEPTION: Cannot resolve all parameters for '$c_Langellolite_StoryService'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that '$c_Langellolite_StoryService' is decorated with Injectable."

In fact I got the same errors in 04, 05 and 06.

the 06 got "@Injectable
class TodoStore {"

I think, It needs something like: 

"class AngelloLite( @Inject storyService: StoryService) {"

but I don't know what to do

by the yesterday 05 it worked,

**Comment by jokade** [comment]
Thanks for the report; I've refactored the DI logic, which broke the examples. It should work now.

**Comment by elyphas** [comment]
Hi, good day, angulate2 looks great, but I had a problem again with
angelloLite, in the file AngelloLite.scala, line 18:

I changed the line for this.

 providers = @@[StoryService, HTTP_PROVIDERS] //:+

and now it works.

Thanks, for the work.

2016-02-06 1:38 GMT-06:00 jokade notifications@github.com:

> Thanks for the report; I've refactored the DI logic, which broke the
> examples. It should work now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jokade/angulate2-examples/issues/1#issuecomment-180714104
> .

## 

JCesar

**Comment by jokade** [comment]
That was due to an inconsitent state of the examples and the angulate2 lib; should be solved now.
